- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: Config nginx
      shell: echo "Hello World" > /var/www/html/index.html

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
